import Head from 'next/head'
import Header from '../layouts/Header'
import { useEffect, useState } from 'react'
import Loading from '../layouts/Loading'
import Home from './Home'
import { GetStaticProps } from 'next'
import { Projects, Skills } from '../typings'
import { fetchSkills } from '../utils/fetchSkills'
import { fetchProjects } from '../utils/fetchProjects'

type Props = {
  skills: Skills[]
  projects: Projects[]
}

const IndexPage = ({ skills, projects }: Props) => {
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    setTimeout(() => setLoading(false), 2000)
  })
  return (
    <>
      {loading ?
        <Loading />
        :
        <>
          <Head>
            <title>Akhil Harikumar</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/logo.svg" />
          </Head>

          <Header />
          <Home skills={skills} projects={projects} />
        </>
      }
    </>
  )
}

export default IndexPage

// export const getStaticProps: GetStaticProps<Props> = async () => {
//   const skills: Skills[] = await fetchSkills()
//   const projects: Projects[] = await fetchProjects()
//   return {
//     props: {
//       skills,
//       projects
//     },
//     revalidate: 10
//   }
// }