import Head from 'next/head'
import Header from '../layouts/Header'
import { useEffect, useState } from 'react'
import Loading from '../layouts/Loading'
import Home from './Home'
import { GetStaticProps } from 'next'
import { Skills } from '../typings'
import { fetchSkills } from '../utils/fetchSkills'

type Props = {
  skills: Skills[]
}

const IndexPage = ({ skills }: Props) => {
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    setTimeout(() => setLoading(false), 2000)
  })
  return (
    <>
      {loading ?
        <Loading />
        :
        <div className='snap-y snap-mandatory z-0 h-screen overflow-y-scroll'>
          <Head>
            <title>Akhil Harikumar</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/logo.svg" />
          </Head>

          <Header />
          <Home props={skills} />
        </div>
      }
    </>
  )
}

export default IndexPage

export const getStaticProps: GetStaticProps<Props> = async () => {
  const skills: Skills[] = await fetchSkills()

  return {
    props: {
      skills
    },
    revalidate: 10
  }
}