import Head from 'next/head'
import Header from '../layouts/Header'
import { useEffect, useState } from 'react'
import Loading from '../layouts/Loading'
import Home from './Home'
import { GetStaticProps } from 'next'
import Airtable from 'airtable'
import { fetchRecords } from '../utils/functions'
import SkillSection from './home/SkillSection'
import { Skills } from '../utils/interface'

const IndexPage = () => {

  const [skills, setSkills] = useState<Skills[]>([]);
  const [loading, setLoading] = useState(false)

  const fetchSkills = async () => {
    try {
      const data = await fetchRecords('Skills');
      if (data)
        setSkills(data);
    } catch (e) {
      console.log(e)
    }
  }

  useEffect(() => {

    fetchSkills()
    setTimeout(() => setLoading(false), 2000)
  }, [])
  return (
    <>
      {loading ?
        <Loading />
        :
        <>
          <Head>
            <title>Akhil Harikumar</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/logo.svg" />
          </Head>

          <Header />
          <Home />
          <SkillSection skills={skills} />
        </>
      }
    </>
  )
}

export default IndexPage

// export const getStaticProps: GetStaticProps<Props> = async () => {
//   const skills: Skills[] = await fetchSkills()
//   const projects: Projects[] = await fetchProjects()
//   return {
//     props: {
//       skills,
//       projects
//     },
//     revalidate: 10
//   }
// }